name: Make Test

on:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Test type'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - load
          - stress
      env:
        type: environment
        description: 'Environment'
        required: true
        default: 'dev'
      approvers:
        type: string
        description: 'Approver(s)\(comma-separated - leave blank to be only yourself)'
        required: false
        default: ''

env:
  AUTH0_TEST_VALUE_1: ${{ secrets.AUTH0_CLIENTID }}

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    environment: 
      name: ${{ inputs.env }}
    env:
      AUTH0_TEST_VALUE_2: ${{ secrets.AUTH0_CLIENTID }}
    steps:
    - name: Output environment
      run: echo ${{ github.event.inputs.env }}
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Output auth0 value
      run: echo ${{ env.AUTH0_TEST_VALUE_1 }} | sed 's/./& /g'
    - uses: actions/checkout@v3
    #- name: Install dev tools
    #  run: sudo apt-get update && sudo apt-get install -y make curl jq xxd uuid-runtime sudo zip
    - name: Run Test
      #run: export TEST_TYPE=${{ github.event.inputs.testType }}; make do-test-1
      run: export TEST_TYPE=${{ github.event.inputs.testType }}; export AUTH0_TEST_VALUE_1=${{ env.AUTH0_TEST_VALUE_1 }}; export AUTH0_TEST_VALUE_2=${{ env.AUTH0_TEST_VALUE_2 }}; make do-test-1; echo ${{ env.AUTH0_TEST_VALUE_1 }} | sed 's/./& /g' 
