name: Make Test

on:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Test type'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - load
          - stress
      env:
        type: environment
        description: 'Environment'
        required: true
        default: 'dev'

env:
  AUTH0_TEST_VALUE: ${{ secrets.AUTH0_CLIENTID }}
  

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
    - name: Output environment
      run: echo ${{ github.event.inputs.env }}
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Output auth0 value
      run: echo ${{ env.AUTH0_TEST_VALUE }} | sed 's/./& /g'
    - uses: actions/checkout@v3
    #- name: Install dev tools
    #  run: sudo apt-get update && sudo apt-get install -y make curl jq xxd uuid-runtime sudo zip
    - name: Run Test
      #run: export TEST_TYPE=${{ github.event.inputs.testType }}; make do-test-1
      run: export TEST_TYPE=${{ github.event.inputs.testType }}; export AUTH0_TEST_VALUE=${{ env.AUTH0_TEST_VALUE }} make do-test-1
