# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven.

name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Run Python Script
      uses: jannekem/run-python-script-action@v1.2
      with:
        script: print("testing python script, again 4")
    - name: test ssh access
      run: ssh localtest '~/testscript.sh'
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: 'aarch64'
        cache: maven
    - name: what directory am I in?
      run: pwd
    - name: run a shell script in the codebase
      run: |
        set -x
        chmod a+x ./scripts/test1.sh
        ./scripts/test1.sh ${{ github.run_number }}
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        echo secret: ${{ secrets.TEST_PASSWORD }}
        pwd
        ls -la
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
